apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: usersapi
    type: "users-api"
  name: usersapi
spec: 
  type: NodePort
  selector: 
    app: usersapi
    type: "users-api"
  ports:
  - name: usersapi
    port: 3000
    targetPort: 3000
    nodePort: 30030

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersapi
      type: "users-api"
  template:
    metadata:
      labels:
        app: usersapi
        type: "users-api"
    spec:
      containers:
      - name: users-api
        image: users-api:v.1.0.0
        stdin: true
        tty: true
        ports:
        - containerPort: 3000
        imagePullPolicy: Never