apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: enrollapi
    type: "enroll-api"
  name: enrollapi
spec: 
  type: NodePort
  selector: 
    app: enrollapi
    type: "enroll-api"
  ports:
  - name: enrollapi
    port: 3001
    targetPort: 3001
    nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollapi
      type: "enroll-api"
  template:
    metadata:
      labels:
        app: enrollapi
        type: "enroll-api"
    spec:
      containers:
      - name: enroll-api
        image: enroll:v1.0.1
        stdin: true
        tty: true
        ports:
        - containerPort: 3001
        env:
        - name: usersAPIEndpoint
          value: roost-worker1:30001
        readinessProbe:
          httpGet:
            path: /api/status
            port: 3001
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/status
            port: 3001
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 100m
            memory: 120Mi
          requests:
            cpu: 50m
            memory: 60Mi
        imagePullPolicy: Never