apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: enrollapi
    type: "enroll-api"
  name: enrollapi
spec: 
  type: NodePort
  selector: 
    app: enrollapi
    type: "enroll-api"
  ports:
  - name: enrollapi
    port: 3002
    targetPort: 3002
    nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollapi
      type: "enroll-api"
  template:
    metadata:
      labels:
        app: enrollapi
        type: "enroll-api"
    spec:
      containers:
      - name: enroll-api
        image: enroll:v1
        stdin: true
        tty: true
        ports:
        - containerPort: 3002
        env:
        - name: usersAPIEndpoint
          value: usersapi:3003
        - name: port
          value: "3002"
        resources:
          limits:
            cpu: 100m
            memory: 120Mi
          requests:
            cpu: 50m
            memory: 60Mi
        imagePullPolicy: Never