apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: enrollapi
    type: "enroll-api"
  name: enrollapi
spec: 
  type: NodePort
  selector: 
    app: enrollapi
    type: "enroll-api"
  ports:
  - name: enrollapi
    port: 3001
    targetPort: 3001
    nodePort: 30031

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollapi
      type: "enroll-api"
  template:
    metadata:
      labels:
        app: enrollapi
        type: "enroll-api"
    spec:
      containers:
      - name: enroll-api
        image: enroll-api:v.1.0.0
        stdin: true
        tty: true
        ports:
        - containerPort: 3001
        imagePullPolicy: Never