apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: usersapi
    type: "users-api"
  name: usersapi
spec: 
  type: NodePort
  selector: 
    app: usersapi
    type: "users-api"
  ports:
  - name: usersapi
    port: 3003
    targetPort: 3003
    nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersapi
      type: "users-api"
  template:
    metadata:
      labels:
        app: usersapi
        type: "users-api"
    spec:
      containers:
      - name: users-api
        image: users:v1
        stdin: true
        tty: true
        ports:
        - containerPort: 3003
        readinessProbe:
          httpGet:
            path: /api/status
            port: 3003
          initialDelaySeconds: 2
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/status
            port: 3003
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            cpu: 100m
            memory: 120Mi
          requests:
            cpu: 50m
            memory: 60Mi
        imagePullPolicy: Never